name: build-client

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@vlatest
      - name: Build and push
        uses: docker/build-push-action@latest
        with:
          context: .
          push: false
          file: client.Dockerfile
          build-args: |
            HOST_DS=http://localhost:8080/,
            HOST_ST=ws://localhost:8081,
            MLW=l
          outputs: build
